### ISSUE TITLE
Duplicating first instance of content for each Doc Type

### ISSUE THREAD

**Issue by hifi-phil** [skybrud/Skybrud.Umbraco.GridData.Dtge#1]
Thanks for putting this online, I can see this issue you are having with the control ID in the GridControlDtgeValue line 65
`
Content = DocTypeGridEditorHelper.ConvertValueToContent("0", docTypeAlias, contentValue);
`
The hardcode 0 value will just duplicate the first instance of the doctype as Doc Type Grid Editor caches on this id. Without adding a GUID to the control in GridData itself, I have an alternative solution. I have hashed the value to create a unique id for the content.

```
        public string GetControlId(string input)
        {
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                return BitConverter.ToString(
                  md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(input))
                ).Replace("-", String.Empty);
            }
        }
```

Can't think of an easier way to do it atm

**Comment by abjerner** [comment]
Wow. We haven't even released this yet, so great to see some feedback already 👍 

DTGE already generates a unique GUID for each control, which we can use. I have some WIP code where this has already been fixed, but I haven't pushed this yet. I will make sure to do so ;)

**Comment by hifi-phil** [comment]
Ah, sorry for jumping the gun! I was using both the GridData and GridData.LeBlender and thought you might have a similar plugin for DTGE. I will look out for your new release. 

BTW thanks for a great plugin in GridData, it makes it possible to work with the Grid

**Comment by abjerner** [comment]
Hi @hifi-phil 

As we haven't had a need for this package ourselves, and other things taking my time, I didn't get around to wrapping up this package and creating a release for it.

I'm now starting to look at this for Umbraco 9, so decided put the last pieces for Umbraco 8 together as well, which resulted in this release:

https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge/releases/tag/v2.0.0

Like I wrote in my last comment (so long long ago 🙃), I already had a fix for the ID back then, which is now also part of this release 😉
